### PR TITLE
add fire

### PR DESCRIPTION
**Pull request by CJ-Wright**
add fire and ipython

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@conda-forge/staged-recipes any thoughts as to why the windows py36 builds are broken?

**Comment by jakirkham** [comment]
Did you solve the issue?

FYI please remember to fork and submit the PR from your fork. Packages release as soon as they are passing if a branch on the main feedstock is used.

**Comment by CJ-Wright** [comment]
Thank you for the reminder!

No I didn't resolve the issue (I just removed py36 from the build).
It seemed to have some issues with locks and not removing files here is the relevant build:
https://ci.appveyor.com/project/conda-forge/billingegroup-feedstock/build/1.0.1/job/431c507fikp2pbeo

**Comment by jakirkham** [comment]
Hmm...unfortunate. 😞 It's weird this happens with Python 3.6. There is a [known issue]( https://github.com/conda/conda/issues/5154 ) with Python 2, but not with Python 3.6 FWICT. Would recommend raising an issue with `conda` and see if they have any suggestions.

**Pull request merged**
